<?php
return [
    'name' => 'Memo',
    'env' => getenv('APP_ENV') ?: 'production',
    'base_url' => getenv('APP_URL') ?: '',
    'timezone' => 'Asia/Shanghai',
    'database' => [
        'path' => __DIR__ . '/../memo.sqlite',
    ],
    'uploads' => [
        'path' => __DIR__ . '/../storage/uploads',
        'max_bytes' => 15 * 1024 * 1024,
        'allowed_mimes' => [
            'image/png' => 'png',
            'image/jpeg' => 'jpg',
            'image/webp' => 'webp',
            'image/gif' => 'gif',
            'image/svg+xml' => 'svg',
            'image/avif' => 'avif',
            'image/bmp' => 'bmp',
            'image/x-icon' => 'ico',
            'application/pdf' => 'pdf',
            'application/zip' => 'zip',
            'application/x-zip-compressed' => 'zip',
            'application/x-rar-compressed' => 'rar',
            'application/vnd.rar' => 'rar',
            'application/msword' => 'doc',
            'application/vnd.openxmlformats-officedocument.wordprocessingml.document' => 'docx',
            'application/vnd.ms-word.document.macroenabled.12' => 'docm',
            'application/vnd.openxmlformats-officedocument.wordprocessingml.template' => 'dotx',
            'application/vnd.ms-word.template.macroenabled.12' => 'dotm',
            'application/vnd.ms-excel' => 'xls',
            'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet' => 'xlsx',
            'application/vnd.ms-excel.sheet.macroenabled.12' => 'xlsm',
            'application/vnd.ms-excel.sheet.binary.macroenabled.12' => 'xlsb',
            'application/vnd.openxmlformats-officedocument.spreadsheetml.template' => 'xltx',
            'application/vnd.ms-excel.template.macroenabled.12' => 'xltm',
            'text/plain' => 'txt',
            'text/markdown' => 'md',
            'text/x-markdown' => 'md',
            'text/csv' => 'csv',
            'text/tab-separated-values' => 'tsv',
            'text/x-log' => 'log',
            'application/json' => 'json',
            'text/json' => 'json',
            'text/yaml' => 'yaml',
            'application/yaml' => 'yaml',
            'text/x-yaml' => 'yaml',
            'video/mp4' => 'mp4',
            'video/quicktime' => 'mov',
            'video/x-matroska' => 'mkv',
            'video/webm' => 'webm',
            'video/x-msvideo' => 'avi',
            'video/mpeg' => 'mpeg',
            'audio/mpeg' => 'mp3',
            'audio/mp3' => 'mp3',
            'audio/ogg' => 'ogg',
            'audio/opus' => 'opus',
            'audio/wav' => 'wav',
            'audio/x-wav' => 'wav',
            'audio/webm' => 'weba',
            'audio/mp4' => 'm4a',
            'audio/aac' => 'aac',
            'audio/flac' => 'flac',
        ],
    ],
];
