<?php
return [
    'name' => 'Memo',
    'env' => getenv('APP_ENV') ?: 'production',
    'base_url' => getenv('APP_URL') ?: '',
    'timezone' => 'Asia/Shanghai',
    'database' => [
        'path' => __DIR__ . '/../memo.sqlite',
    ],
    'uploads' => [
        'path' => __DIR__ . '/../storage/uploads',
        'max_bytes' => 15 * 1024 * 1024,
        'allowed_mimes' => [
            'image/png' => 'png',
            'image/jpeg' => 'jpg',
            'image/webp' => 'webp',
            'image/gif' => 'gif',
            'image/svg+xml' => 'svg',
            'image/avif' => 'avif',
            'image/bmp' => 'bmp',
            'image/x-icon' => 'ico',
            'application/pdf' => 'pdf',
            'application/zip' => 'zip',
            'application/x-zip-compressed' => 'zip',
            'text/plain' => 'txt',
            'text/markdown' => 'md',
            'text/x-markdown' => 'md',
            'text/csv' => 'csv',
            'application/json' => 'json',
            'text/json' => 'json',
            'text/yaml' => 'yaml',
            'application/yaml' => 'yaml',
            'text/x-yaml' => 'yaml',
            'text/tab-separated-values' => 'tsv',
            'text/x-log' => 'log',
            'video/mp4' => 'mp4',
            'video/quicktime' => 'mov',
            'video/x-matroska' => 'mkv',
            'video/webm' => 'webm',
            'video/x-msvideo' => 'avi',
            'video/mpeg' => 'mpeg',
        ],
    ],
];
